Update README.md
I tried to follow the example and ran into this error message:

```
RuntimeError: No suitable template parameter can be found.
```

Turns out `itk.elastix_registration_method` returns a tuple:

```
(<itk.itkImagePython.itkImageF2; proxy of <Swig Object of type 'itkImageF2 *' at 0x7f248994abd0> >, <itk.elxParameterObjectPython.elastixParameterObject; proxy of <Swig Object of type 'elastixParameterObject *' at 0x7f248994aba0> >)
```

And that error message popped up when I passed the tuple to `sitk.array_from_image`. I guess adding `params` will remind people what they get from this function call.

I'm running ITK 5.1.0.post3 and `itk-elastix` 0.6.2